// Obscura bootstrap source manifest.
//
// The build script concatenates these files in order into one classic script.
// The top-level directories mirror HaHaVM's config/tools/env split, while
// env/ is grouped by browser capability. The manifest order remains load-
// bearing because the source is one lexical V8 bootstrap, not ES modules.
// @obscura-module config/bootstrap.js
// @obscura-module tools/script-loader.js
// @obscura-module tools/dom-query.js
// @obscura-module tools/error-events.js
// @obscura-module tools/timers.js
// @obscura-module tools/scheduler.js
// @obscura-module env/events/message-channel.js
// @obscura-module env/events/message-port.js
// @obscura-module env/events/message-channel-object.js
// @obscura-module env/css/style-declaration.js
// @obscura-module env/dom/clone.js
// @obscura-module env/events/support/state.js
// @obscura-module env/events/support/listeners.js
// @obscura-module env/events/event-target.js
// @obscura-module env/events/observable.js
// @obscura-module env/events/subscriber.js
// @obscura-module env/events/observable-object.js
// @obscura-module env/dom/node.js
// @obscura-module env/dom/event-target-object.js
// @obscura-module env/dom/node-object.js
// @obscura-module env/dom/character-data.js
// @obscura-module env/dom/text.js
// @obscura-module env/dom/comment.js
// @obscura-module env/dom/tokens.js
// @obscura-module env/dom/text-url.js
// @obscura-module env/dom/cdatasection.js
// @obscura-module env/dom/processing-instruction.js
// @obscura-module env/dom/input-parser.js
// @obscura-module env/dom/html-parser.js
// @obscura-module env/dom/named-node-map.js
// @obscura-module env/dom/keyframe-effect.js
// @obscura-module env/dom/animation.js
// @obscura-module env/dom/document-timeline.js
// @obscura-module env/dom/element-object.js
// @obscura-module tools/interaction.js
// @obscura-module env/security/permissions-policy-support.js
// @obscura-module env/security/permissions-policy-objects.js
// @obscura-module env/security/view-transition.js
// @obscura-module env/dom/document.js
// @obscura-module env/dom/document-fragments.js
// @obscura-module env/dom/document-fragment.js
// @obscura-module env/dom/document-type.js
// @obscura-module env/dom/support/collections.js
// @obscura-module env/dom/support/window-named-properties.js
// @obscura-module env/media/text-tracks.js
// @obscura-module env/media/text-track-cue.js
// @obscura-module env/media/vtt-cue.js
// @obscura-module env/media/text-track-cue-list.js
// @obscura-module env/media/text-track.js
// @obscura-module env/media/text-track-list.js
// @obscura-module env/performance/resource-timing.js
// @obscura-module env/media/image.js
// @obscura-module env/media/media-elements.js
// @obscura-module env/media/time-ranges.js
// @obscura-module env/media/video-playback-quality.js
// @obscura-module env/media/html-media-element.js
// @obscura-module env/media/html-video-element.js
// @obscura-module env/media/html-audio-element.js
// @obscura-module env/media/html-object-element.js
// @obscura-module env/media/html-track-element.js
// @obscura-module env/dom/iframe-element.js
// @obscura-module env/frame/realms.js
// @obscura-module env/window/location.js
// @obscura-module env/window/plugins.js
// @obscura-module env/fingerprint/navigator.js
// @obscura-module env/fingerprint/support/webgl-profile.js
// @obscura-module env/fingerprint/webgl.js
// @obscura-module env/fingerprint/support/screen-state.js
// @obscura-module env/fingerprint/screen.js
// @obscura-module tools/encoding-base64.js
// @obscura-module env/network/fetch.js
// @obscura-module env/network/headers.js
// @obscura-module env/network/xhr.js
// @obscura-module env/network/url.js
// @obscura-module env/network/request.js
// @obscura-module env/network/response.js
// @obscura-module env/dom/child-node.js
// @obscura-module env/render/resize-objects.js
// @obscura-module env/render/resize.js
// @obscura-module tools/encoding-media-query.js
// @obscura-module env/css/computed-style.js
// @obscura-module env/css/cssom.js
// @obscura-module env/css/css-rule.js
// @obscura-module env/css/css-style-rule.js
// @obscura-module env/css/css-rule-list.js
// @obscura-module env/css/css-style-sheet.js
// @obscura-module env/css/style-sheet-list.js
// @obscura-module env/css/mutation-observer.js
// @obscura-module env/css/shadow-root.js
// @obscura-module env/dom/shadow-custom-elements.js
// @obscura-module env/dom/custom-element-registry.js
// @obscura-module env/dom/element-internals.js
// @obscura-module env/render/intersection-entry.js
// @obscura-module env/render/intersection.js
// @obscura-module env/events/dom-exception.js
// @obscura-module env/events/event-object.js
// @obscura-module env/events/input-device-capabilities.js
// @obscura-module env/events/custom-event.js
// @obscura-module env/events/mouse-event.js
// @obscura-module env/events/keyboard-event.js
// @obscura-module env/events/focus-event.js
// @obscura-module env/events/input-event.js
// @obscura-module env/events/error-event.js
// @obscura-module env/events/pointer-event.js
// @obscura-module env/events/animation-event.js
// @obscura-module env/events/transition-event.js
// @obscura-module env/events/ui-event.js
// @obscura-module env/events/wheel-event.js
// @obscura-module env/events/composition-event.js
// @obscura-module env/events/pop-state-event.js
// @obscura-module env/events/hash-change-event.js
// @obscura-module env/events/message-event.js
// @obscura-module env/events/progress-event.js
// @obscura-module env/events/clipboard-event.js
// @obscura-module env/events/submit-event.js
// @obscura-module env/events/toggle-event.js
// @obscura-module env/events/promise-rejection-event.js
// @obscura-module env/events/storage-event.js
// @obscura-module env/events/security-policy-violation-event.js
// @obscura-module env/events/support/input-dispatch.js
// @obscura-module env/events/abort-controller.js
// @obscura-module env/file/blob.js
// @obscura-module env/network/form-data.js
// @obscura-module env/dom/xml-parser.js
// @obscura-module env/dom/dom-parser.js
// @obscura-module env/dom/xml-serializer.js
// @obscura-module env/performance/support/clock.js
// @obscura-module env/performance/performance.js
// @obscura-module env/performance/memory-info.js
// @obscura-module env/performance/timeline-state.js
// @obscura-module env/performance/performance-entry.js
// @obscura-module env/performance/performance-mark.js
// @obscura-module env/performance/performance-measure.js
// @obscura-module env/performance/performance-resource-timing.js
// @obscura-module env/performance/performance-navigation-timing.js
// @obscura-module env/performance/performance-paint-timing.js
// @obscura-module env/performance/performance-observer-entry-list.js
// @obscura-module env/performance/observer.js
// @obscura-module env/performance/user-timing.js
// @obscura-module env/performance/lifecycle-hooks.js
// @obscura-module env/dom/document-all.js
// @obscura-module tools/fonts.js
// @obscura-module env/crypto/crypto-clone.js
// @obscura-module env/storage/storage-history.js
// @obscura-module env/navigation/navigation.js
// @obscura-module env/window/geometry.js
// @obscura-module env/dom/geometry-objects.js
// @obscura-module env/html/image-constructor.js
// @obscura-module env/media/audio-constructor.js
// @obscura-module env/file/file-reader.js
// @obscura-module env/css/supports.js
// @obscura-module env/html/link.js
// @obscura-module env/html/input-element.js
// @obscura-module env/html/body-element.js
// @obscura-module env/html/form-element.js
// @obscura-module env/html/interface-aliases.js
// @obscura-module env/html/svg-elements.js
// @obscura-module env/dom/xml-mixins.js
// @obscura-module tools/webidl-mixins.js
// @obscura-module env/dom/html-collection.js
// @obscura-module env/dom/node-list.js
// @obscura-module env/dom/ranges-selection.js
// @obscura-module env/dom/support/range.js
// @obscura-module env/dom/range-object.js
// @obscura-module env/dom/static-range.js
// @obscura-module env/dom/selection.js
// @obscura-module env/dom/ranges-postlude.js
// @obscura-module env/media/canvas-primitives.js
// @obscura-module env/dom/aria.js
// @obscura-module env/media/support/text-metrics-state.js
// @obscura-module env/media/text-metrics.js
// @obscura-module env/media/canvas.js
// @obscura-module env/media/canvas-element.js
// @obscura-module env/media/support/audio-context-behavior.js
// @obscura-module env/media/audio-buffer.js
// @obscura-module env/media/audio-context.js
// @obscura-module env/media/offline-audio-context.js
// @obscura-module env/media/support/speech-synthesis-behavior.js
// @obscura-module env/media/support/media-stream-behavior.js
// @obscura-module env/media/speech-synthesis.js
// @obscura-module env/media/media-stream.js
// @obscura-module env/media/audio.js
// @obscura-module env/media/support/webrtc-state.js
// @obscura-module env/media/webrtc.js
// @obscura-module env/media/rtc-peer-connection.js
// @obscura-module env/media/rtc-rtp-sender.js
// @obscura-module env/media/rtc-rtp-receiver.js
// @obscura-module env/media/rtc-session-description.js
// @obscura-module env/media/rtc-ice-candidate.js
// @obscura-module env/storage/indexeddb-cache.js
// @obscura-module env/input/support/media-capabilities-behavior.js
// @obscura-module env/input/capabilities.js
// @obscura-module env/input/keyboard.js
// @obscura-module env/input/keyboard-layout-map.js
// @obscura-module env/input/keyboard-object.js
// @obscura-module env/media/support/webgpu-collections.js
// @obscura-module env/media/gpu-constants.js
// @obscura-module env/media/webgpu.js
// @obscura-module env/media/gpu-supported-limits.js
// @obscura-module env/media/gpu-supported-features.js
// @obscura-module env/media/gpu-adapter-info.js
// @obscura-module env/media/gpu-device.js
// @obscura-module env/media/gpu-adapter.js
// @obscura-module env/media/gpu.js
// @obscura-module env/media/gpu-canvas.js
// @obscura-module env/worker/dedicated-worker.js
// @obscura-module env/window/scroll-postmessage.js
// @obscura-module env/streams/support/readable-behavior.js
// @obscura-module env/streams/readable-stream.js
// @obscura-module env/streams/support/writable-behavior.js
// @obscura-module env/streams/writable-stream.js
// @obscura-module env/streams/support/transform-behavior.js
// @obscura-module env/streams/transform-stream.js
// @obscura-module env/streams/support/text-stream-behavior.js
// @obscura-module env/streams/text-encoder-stream.js
// @obscura-module env/streams/text-decoder-stream.js
// @obscura-module env/crypto/subtle.js
// @obscura-module env/network/support/socket-listeners.js
// @obscura-module env/network/event-source.js
// @obscura-module env/network/websocket.js
// @obscura-module env/network/broadcast-channel.js
// @obscura-module env/network/media-query-list.js
// @obscura-module env/network/sockets.js
// @obscura-module env/worker/shared-worker.js
// @obscura-module env/media/media-source-worklet.js
// @obscura-module env/security/trusted-types.js
// @obscura-module config/postlude.js
// @obscura-module config/page-init.js
// @obscura-module config/window-surface.js
// @obscura-module config/surface-finalize.js
// @obscura-module config/webidl-branding.js
