// Obscura bootstrap source manifest.
//
// The build script concatenates these files in order into one classic script.
// The top-level directories mirror HaHaVM's config/tools/env split, while
// env/ is grouped by browser capability. The manifest order remains load-
// bearing because the source is one lexical V8 bootstrap, not ES modules.
// @obscura-module config/bootstrap.js
// @obscura-module tools/script-loader.js
// @obscura-module tools/dom-query.js
// @obscura-module tools/error-events.js
// @obscura-module tools/timers.js
// @obscura-module tools/scheduler.js
// @obscura-module env/events/message-channel.js
// @obscura-module env/css/style-declaration.js
// @obscura-module env/dom/clone.js
// @obscura-module env/events/event-target.js
// @obscura-module env/events/observable.js
// @obscura-module env/dom/node.js
// @obscura-module env/dom/tokens.js
// @obscura-module env/dom/text-url.js
// @obscura-module env/dom/input-parser.js
// @obscura-module env/dom/html-parser.js
// @obscura-module env/dom/element.js
// @obscura-module tools/interaction.js
// @obscura-module env/security/permissions-policy.js
// @obscura-module env/dom/document.js
// @obscura-module env/dom/document-fragments.js
// @obscura-module env/media/text-tracks.js
// @obscura-module env/performance/resource-timing.js
// @obscura-module env/media/image.js
// @obscura-module env/media/media-elements.js
// @obscura-module env/dom/iframe-element.js
// @obscura-module env/frame/realms.js
// @obscura-module env/window/location.js
// @obscura-module env/window/plugins.js
// @obscura-module env/fingerprint/navigator.js
// @obscura-module env/fingerprint/webgl.js
// @obscura-module env/fingerprint/screen.js
// @obscura-module tools/encoding-base64.js
// @obscura-module env/network/fetch.js
// @obscura-module env/network/headers.js
// @obscura-module env/network/xhr.js
// @obscura-module env/network/url.js
// @obscura-module env/network/request.js
// @obscura-module env/network/response.js
// @obscura-module env/dom/child-node.js
// @obscura-module env/render/resize.js
// @obscura-module tools/encoding-media-query.js
// @obscura-module env/css/computed-style.js
// @obscura-module env/css/cssom.js
// @obscura-module env/dom/shadow-custom-elements.js
// @obscura-module env/render/intersection.js
// @obscura-module env/events/dom-exception.js
// @obscura-module env/events/input-events.js
// @obscura-module env/events/event-classes.js
// @obscura-module env/events/abort-controller.js
// @obscura-module env/file/blob.js
// @obscura-module env/network/form-data.js
// @obscura-module env/dom/xml-parser.js
// @obscura-module env/performance/performance.js
// @obscura-module env/dom/document-all.js
// @obscura-module tools/fonts.js
// @obscura-module env/crypto/crypto-clone.js
// @obscura-module env/storage/storage-history.js
// @obscura-module env/navigation/navigation.js
// @obscura-module env/window/geometry.js
// @obscura-module env/css/supports.js
// @obscura-module env/html/link.js
// @obscura-module env/html/form-elements.js
// @obscura-module env/dom/xml-mixins.js
// @obscura-module tools/webidl-mixins.js
// @obscura-module env/dom/collections.js
// @obscura-module env/dom/ranges-selection.js
// @obscura-module env/media/canvas-primitives.js
// @obscura-module env/dom/aria.js
// @obscura-module env/media/canvas.js
// @obscura-module env/media/audio.js
// @obscura-module env/media/webrtc.js
// @obscura-module env/storage/indexeddb-cache.js
// @obscura-module env/input/capabilities.js
// @obscura-module env/input/keyboard.js
// @obscura-module env/media/webgpu.js
// @obscura-module env/media/gpu-canvas.js
// @obscura-module env/worker/dedicated-worker.js
// @obscura-module env/window/scroll-postmessage.js
// @obscura-module env/streams/streams.js
// @obscura-module env/crypto/subtle.js
// @obscura-module env/dom/geometry.js
// @obscura-module env/network/sockets.js
// @obscura-module env/worker/shared-worker.js
// @obscura-module env/media/media-source-worklet.js
// @obscura-module env/security/trusted-types.js
// @obscura-module config/postlude.js
// @obscura-module config/page-init.js
// @obscura-module config/window-surface.js
// @obscura-module config/surface-finalize.js
